# Run lint for file errors
# Run unit tests
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 13.12.0

    - name: Install dependencies
      run: npm install
    
    - name: Lint check
      run: ng lint
    - name: Unit tests
      run: ng test
