# Run lint for file errors
# Run unit tests
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 13.12.0

    - name: Install dependencies
      run: npm install
    
    - name: Lint check
      run: npm run ng lint

